&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;title&gt;Exam Schedule&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;h1&gt;Exam Schedule&lt;/h1&gt;
    &lt;p&gt;{{ $message }}&lt;/p&gt;
    &lt;p&gt;Best regards,&lt;br&gt;Exam Management System&lt;/p&gt;
&lt;/body&gt;
&lt;/html&gt;
